export const ADJUST_VOLUME = "ADJUST_VOLUME";
export const UPDATE_DISPLAY_TEXT = "UPDATE_DISPLAY_TEXT";
export const SET_PRESSED_KEY = "SET_PRESSED_KEY";
export const RESET_PRESSED_KEY = "RESET_PRESSED_KEY";
